import path from 'path';
import { SpecializationsMatchingEngine, type WordSynonym, type WordWeight } from './specializations-matching-engine';

export class SpecializationsMatchingFactory {
    public static async create(): Promise<SpecializationsMatchingEngine> {
        const csvPath = path.resolve(process.cwd(), 'data/specializations/specializations.csv');
        const fileContent = await Bun.file(csvPath).text();

        const specNames = fileContent
            .split('\n')
            .map(line => line.trim())
            .filter(line => line && line !== '"Название"')
            .map(line => line.replace(/^"(.*)"$/, '$1'));

        // Filtered and refined synonyms (removed hyper-generalizing ones like frontend->разработчик)
        const synonymsData: WordSynonym[] = [
            { src: 'dev', dst: 'разработчик' },
            { src: 'manual', dst: 'ручной' },
            { src: 'automation', dst: 'авто' },
            { src: 'director', dst: 'директор' },
            { src: 'head', dst: 'руководитель' },
            { src: 'cpo', dst: 'директор' },
            { src: 'cto', dst: 'директор' },
            { src: 'cio', dst: 'директор' },
            { src: 'cdo', dst: 'директор' },
            { src: 'product', dst: 'продукт' },
            { src: 'project', dst: 'проект' },
            { src: 'delivery', dst: 'деливери' },
            { src: 'teamlead', dst: 'руководитель' },
            { src: 'team', dst: null },
            { src: 'senior', dst: null },
            { src: 'middle', dst: null },
            { src: 'junior', dst: null },
            { src: 'staff', dst: null },
            { src: 'principal', dst: null },
            { src: 'expert', dst: null },
            { src: 'specialist', dst: null },
            { src: 'главный', dst: null },
            { src: 'ведущий', dst: null },
            { src: 'старший', dst: null },
            { src: 'начальник', dst: null },
            { src: 'заместитель', dst: null },
            { src: 'зам', dst: null },
            { src: '1c', dst: '1с' },
            { src: 'pm', dst: 'проект' },
            { src: 'hr', dst: 'персонал' },
            { src: 'recruit', dst: 'рекрутер' },
            { src: 'legal', dst: 'юрист' },
            { src: 'lawyer', dst: 'юрист' },
            { src: 'accounting', dst: 'бухгалтер' },
            { src: 'finan', dst: 'финанс' },
            { src: 'wms', dst: 'склад' },
            { src: 'склад', dst: 'склад' },
            { src: 'маркетолог', dst: 'маркетолог' },
            { src: 'performance', dst: 'эффективность' },
            { src: 'transformation', dst: 'трансформация' },
            { src: 'digital', dst: 'цифровой' },
            { src: 'data', dst: 'дата' },
            { src: 'ai', dst: 'ии' },
            { src: 'ml', dst: 'ии' },
            { src: 'vision', dst: 'ии' },
            { src: 'cv', dst: 'ии' },
            { src: 'unreal', dst: 'разработчик' },
            { src: 'unity', dst: 'разработчик' },
            { src: 'game', dst: 'разработчик' },
            { src: 'abap', dst: 'abap' },
            { src: 'basis', dst: 'basis' },
            { src: 'hcm', dst: 'hcm' },
            { src: 'ewm', dst: 'ewm' },
            { src: 'bw', dst: 'bw' },
            { src: 'mm', dst: 'mm' },
            { src: 'sd', dst: 'sd' },
            { src: 'pp', dst: 'pp' },
            { src: 'pi', dst: 'pi' },
            { src: 'po', dst: 'po' },
            { src: 'fi', dst: 'fi' },
            { src: 'co', dst: 'co' },
            { src: 'network', dst: 'сетевой' },
            { src: 'система', dst: 'системный' },
            { src: 'system', dst: 'системный' },
            { src: 'administration', dst: 'администратор' },
            { src: 'administrator', dst: 'администратор' },
            { src: 'админ', dst: 'администратор' },
            { src: 'инфраструктура', dst: 'инфраструктура' },
            { src: 'agile', dst: 'agile' },
            { src: 'coach', dst: 'коуч' },
            { src: 'поддержка', dst: 'поддержка' },
            { src: 'сопровождение', dst: 'сопровождение' },
            { src: 'tech', dst: 'тех' },
            { src: 'technical', dst: 'тех' },
            { src: 'технический', dst: 'тех' },
            { src: 'информационный', dst: 'инфо' },
            { src: 'безопасность', dst: 'безопасность' },
            { src: 'security', dst: 'безопасность' },
            { src: 'cyber', dst: 'безопасность' },
            { src: 'cloud', dst: 'облако' },
            { src: 'sre', dst: 'sre' },
            { src: 'javascript', dst: 'javascript' },
            { src: 'js', dst: 'javascript' },
            { src: 'node', dst: 'nodejs' },
            { src: 'nodejs', dst: 'nodejs' },
            { src: 'nest', dst: 'nestjs' },
            { src: 'nestjs', dst: 'nestjs' },
            { src: 'ios', dst: 'ios' },
            { src: 'android', dst: 'android' },
            { src: 'мобильный', dst: 'мобильный' },
            { src: 'разработка', dst: 'разработчик' },
            { src: 'аналитика', dst: 'аналитик' },
            { src: 'аналитический', dst: 'аналитик' },
            { src: 'бизнес', dst: 'бизнес' },
            { src: 'продуктовый', dst: 'продукт' },
            { src: 'проектов', dst: 'проект' },
            { src: 'тимлид', dst: 'руководитель' },
            { src: 'техлид', dst: 'руководитель' },
            { src: 'автоматизатор', dst: 'авто' },
            { src: 'автоматизированное', dst: 'авто' },
            { src: 'dba', dst: 'администратор баз данных' },
            { src: 'fintech', dst: null },
            { src: 'retail', dst: null },
            { src: 'bank', dst: null },
            { src: 'trading', dst: null },
            { src: 'crypto', dst: null },
            { src: 'blockchain', dst: null },
            { src: 'web3', dst: null },
            { src: 'llm', dst: 'ии' },
            { src: 'prompt', dst: 'ии' },
            { src: 'orchestrator', dst: 'ии' },
            { src: 'analytics', dst: 'аналитик' },
            { src: 'scientist', dst: 'аналитик' },
            { src: 'science', dst: 'аналитик' },
            { src: 'c#', dst: 'csharp' },
            { src: 'c++', dst: 'cpp' },
            { src: 'of', dst: null },
            { src: 'and', dst: null },
            { src: 'in', dst: null },
            { src: 'for', dst: null },
            { src: 'with', dst: null },
            { src: 'группы', dst: null },
            { src: 'команды', dst: null },
            { src: 'направления', dst: null },
            { src: 'отдела', dst: null },
            { src: 'сектора', dst: null },
            { src: 'управления', dst: null },
            { src: 'функции', dst: null },
            { src: 'практики', dst: null },
            { src: 'центра', dst: null },
            { src: 'central', dst: null },
            { src: 'center', dst: null },
            { src: 'global', dst: null },
            { src: 'local', dst: null },
            { src: 'regional', dst: null },
            { src: 'area', dst: null },
            { src: 'chief', dst: null },
            { src: 'officer', dst: null },
            { src: 'development', dst: null },
            { src: 'management', dst: null },
            { src: 'controller', dst: null },
            { src: 'associate', dst: null },
            { src: 'assistant', dst: null },
            { src: 'ассистент', dst: null },
            { src: 'помощник', dst: null },
            { src: 'стажер', dst: null },
            { src: 'intern', dst: null },
            { src: 'trainee', dst: null },
            { src: 'разработки', dst: null },
            { src: 'проектами', dst: null },
            { src: 'информационных', dst: null },
            { src: 'технологий', dst: null },
            { src: 'it', dst: null },
            { src: 'ит', dst: null },
        ];

        // Combine base weights with specialized ones
        const weightsData: WordWeight[] = [
            { word: 'frontend', weight: 0.5 },
            { word: 'backend', weight: 0.5 },
            { word: 'react', weight: 1.2 },
            { word: 'angular', weight: 1.2 },
            { word: 'vue', weight: 1.2 },
            { word: 'qa', weight: 2.0 },
            { word: 'авто', weight: 1.8 },
            { word: 'java', weight: 1.2 },
            { word: 'python', weight: 1.2 },
            { word: 'javascript', weight: 2.0 },
            { word: 'csharp', weight: 2.0 },
            { word: 'cpp', weight: 2.0 },
            { word: 'php', weight: 1.2 },
            { word: 'go', weight: 2.0 },
            { word: 'kotlin', weight: 2.0 },
            { word: 'swift', weight: 2.0 },
            { word: 'sql', weight: 2.0 },
            { word: 'sap', weight: 2.0 },
            { word: '1с', weight: 1.0 },
            { word: 'ии', weight: 2.0 },
            { word: 'data', weight: 1.5 },
            { word: 'dwh', weight: 1.5 },
            { word: 'bi', weight: 1.5 },
            { word: 'developer', weight: 0.3 },
            { word: 'engineer', weight: 0.3 },
            { word: 'разработчик', weight: 0.3 },
            { word: 'инженер', weight: 0.3 },
            { word: 'менеджер', weight: 0.3 },
            { word: 'руководитель', weight: 0.8 },
            { word: 'аналитик', weight: 0.3 },
            { word: 'дизайнер', weight: 0.3 },
            { word: 'тестировщик', weight: 0.3 },
            { word: 'архитектор', weight: 0.3 },
            { word: 'консультант', weight: 0.2 },
            { word: 'администратор', weight: 0.3 },
            { word: 'специалист', weight: 0.1 },
            { word: 'лид', weight: 0.3 },
            { word: 'devops', weight: 2.5 },
            { word: 'scrum', weight: 2.5 },
            { word: 'jira', weight: 1.5 },
            { word: 'etl', weight: 1.5 },
        ];

        return new SpecializationsMatchingEngine(
            specNames,
            synonymsData,
            weightsData
        );
    }
}
